#!/usr/bin/env python3
"""
master_finder.py — Leo's reverse-calibration tool.

Run this ONCE on the already-calibrated master robot to generate the numbers
every kit builder's calibration depends on:

  1. energizes every servo to the current HOME pose (servo_home from the
     calibration file, or the factory table if none exists),
  2. you nudge each joint until the robot is physically in the REFERENCE
     pose (every joint straight or at exactly 90 deg),
  3. press g (generate): it writes a ready-to-paste replacement for
     tools/master_tables.py containing:
        REFERENCE_POSE_DEG        (the angles you ended at)
        REF_TO_HOME_DELTA_DEG     (home - reference, per channel)
        REFERENCE_JOINT_ANGLES_DEG  *estimated* from the current IK mapping
     The output is printed on exit AND saved to
     ~/.config/corndog/master_tables_generated.py

  NOTE on the theta estimates: they're back-computed from your CURRENT
  mapping offsets (theta = sign * (ref_angle - offset)). If the current
  mapping is slightly off, the estimates inherit that error — sanity-check
  them against the kinematic model (they should be clean values like 0 or
  +/-90 if the reference pose is truly straight/90).

Usage:
    corndog run tools/master_finder.py
    python3 tools/master_finder.py --simulate
"""

from __future__ import annotations

import argparse
import curses
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from corndog_config import (                                   # noqa: E402
    SERVO_CHANNELS, CHANNEL_MAP, LEG_NAMES, JOINT_NAMES,
    load_calibration, config_dir,
)
from servo_rig import Rig, open_rig                            # noqa: E402

STEP_SIZES = [0.1, 0.5, 1.0, 5.0]
ROWS = [(leg, joint) for leg in (0, 1, 2, 3) for joint in (1, 2, 3)]

GRN = "\033[32m"; YLW = "\033[33m"; RED = "\033[31m"; RST = "\033[0m"


def generate_tables(home: dict, ref: dict, mapping: dict) -> str:
    """Build the paste-ready master_tables.py content."""
    ts = datetime.now().isoformat(timespec="seconds")
    L = []
    L.append('#!/usr/bin/env python3')
    L.append('"""')
    L.append('master_tables.py — generated by master_finder.py on ' + ts)
    L.append('Paste this whole file over tools/master_tables.py (keep this header')
    L.append('or rewrite it, either way).')
    L.append('"""')
    L.append('')
    L.append('from corndog_config import SERVO_CHANNELS  # noqa: F401')
    L.append('')
    L.append('# Commanded servo angle (deg) per channel at the REFERENCE pose')
    L.append('REFERENCE_POSE_DEG = {')
    for leg in (0, 1, 2, 3):
        parts = []
        for j in (1, 2, 3):
            ch = CHANNEL_MAP[leg][j]
            parts.append(f"{ch}: {ref[ch]:.1f}")
        L.append(f"    {', '.join(parts)},   # {LEG_NAMES[leg]}")
    L.append('}')
    L.append('')
    L.append('# Signed degrees FROM reference TO home, per channel')
    L.append('REF_TO_HOME_DELTA_DEG = {')
    for leg in (0, 1, 2, 3):
        parts = []
        for j in (1, 2, 3):
            ch = CHANNEL_MAP[leg][j]
            parts.append(f"{ch}: {home[ch] - ref[ch]:+.1f}")
        L.append(f"    {', '.join(parts)},   # {LEG_NAMES[leg]}")
    L.append('}')
    L.append('')
    L.append('# Kinematic theta (deg) at the reference pose, right legs only.')
    L.append('# ESTIMATED from the current mapping — sanity-check these! They')
    L.append('# should be clean values (0, +/-90, ...) if the pose is true.')
    L.append('REFERENCE_JOINT_ANGLES_DEG = {')
    for leg in (1, 3):
        parts = []
        for j in (1, 2, 3):
            ch = CHANNEL_MAP[leg][j]
            sign = mapping[leg][j]["sign"]
            offset = mapping[leg][j]["offset"]
            theta = sign * (ref[ch] - offset)   # sign is +/-1 so 1/sign == sign
            parts.append(f"{j}: {theta:.1f}")
        L.append(f"    {leg}: {{{', '.join(parts)}}},   # {LEG_NAMES[leg]}")
    L.append('}')
    L.append('')
    L.append('')
    L.append('def deltas_ready() -> bool:')
    L.append('    return True')
    L.append('')
    L.append('')
    L.append('def thetas_ready() -> bool:')
    L.append('    return True')
    L.append('')
    return "\n".join(L)


class UI:
    def __init__(self, scr, rig: Rig, home: dict, mapping: dict):
        self.scr = scr
        self.rig = rig
        self.home = home
        self.mapping = mapping
        self.sel = 0
        self.step_i = 2
        self.generated: str | None = None
        self.msg = "Nudge him from HOME into the REFERENCE pose, then press g"
        curses.curs_set(0)
        curses.use_default_colors()
        curses.init_pair(1, curses.COLOR_RED, -1)
        curses.init_pair(2, curses.COLOR_GREEN, -1)
        curses.init_pair(3, curses.COLOR_YELLOW, -1)
        curses.init_pair(4, curses.COLOR_CYAN, -1)
        scr.timeout(150)

    def draw(self):
        scr = self.scr
        scr.erase()
        h, w = scr.getmaxyx()
        A = curses.color_pair(1) | curses.A_BOLD
        G = curses.color_pair(2)
        Y = curses.color_pair(3)
        C = curses.color_pair(4)

        title = " MASTER FINDER — home -> reference recorder "
        scr.addnstr(0, 0, "=" * (w - 1), w - 1, A)
        scr.addnstr(0, max(0, (w - len(title)) // 2), title, w - 1, A)
        if self.rig.simulate:
            scr.addnstr(0, max(0, w - 14), "(SIMULATION)", 12, Y)

        hdr = f"{'':2}{'LEG':<12}{'JOINT':<10}{'CH':>3}  {'ANGLE':>8}  {'HOME':>8}  {'MOVED':>7}  {'PWR':>3}"
        scr.addnstr(2, 2, hdr, w - 3, C | curses.A_BOLD)

        for i, (leg, joint) in enumerate(ROWS):
            ch = CHANNEL_MAP[leg][joint]
            a = self.rig.angles.get(ch)
            hm = self.home[ch]
            row = f"{LEG_NAMES[leg]:<12}{JOINT_NAMES[joint]:<10}{ch:>3}  "
            row += f"{a:8.1f}  " if a is not None else f"{'--':>8}  "
            row += f"{hm:8.1f}  "
            row += (f"{a - hm:+7.1f}  " if a is not None else f"{'--':>7}  ")
            row += " ON" if self.rig.torque.get(ch) else "off"
            y = 3 + i
            if y >= h - 6:
                break
            attr = curses.A_REVERSE | A if i == self.sel else curses.A_NORMAL
            scr.addnstr(y, 2, ("> " if i == self.sel else "  ") + row, w - 3, attr)

        y = 3 + len(ROWS) + 1
        scr.addnstr(y, 2, f"step: {STEP_SIZES[self.step_i]:g} deg   "
                          f"(keys 1-4 = 0.1 / 0.5 / 1 / 5)", w - 3, C)
        scr.addnstr(min(h - 3, y + 2), 2, self.msg, w - 3, G)
        scr.addnstr(h - 2, 2, "up/down select   left/right or -/+ nudge   "
                              "h re-send HOME pose", w - 3, C)
        scr.addnstr(h - 1, 2, "t torque OFF (sel)   T ALL off   e re-enable   "
                              "g GENERATE tables   q quit", w - 3, C)
        scr.refresh()

    def sel_channel(self) -> int:
        leg, joint = ROWS[self.sel]
        return CHANNEL_MAP[leg][joint]

    def nudge(self, direction: int):
        ch = self.sel_channel()
        cur = self.rig.angles.get(ch)
        if cur is None:
            cur = self.home[ch]
        self.rig.goto(ch, cur + direction * STEP_SIZES[self.step_i], ramp=False)
        leg, joint = ROWS[self.sel]
        self.msg = (f"{LEG_NAMES[leg]} {JOINT_NAMES[joint]} (ch {ch}) -> "
                    f"{self.rig.angles[ch]:.1f} deg "
                    f"({self.rig.angles[ch] - self.home[ch]:+.1f} from home)")

    def generate(self):
        ref = {ch: (self.rig.angles.get(ch)
                    if self.rig.angles.get(ch) is not None else self.home[ch])
               for ch in SERVO_CHANNELS}
        self.generated = generate_tables(self.home, ref, self.mapping)
        out = config_dir() / "master_tables_generated.py"
        out.write_text(self.generated, encoding="utf-8")
        self.msg = f"Generated -> {out} (also printed when you quit)"

    def loop(self):
        while True:
            self.draw()
            k = self.scr.getch()
            if k == -1:
                continue
            if k in (ord("q"), 27):
                return
            elif k in (curses.KEY_UP, ord("k")):
                self.sel = (self.sel - 1) % len(ROWS)
            elif k in (curses.KEY_DOWN, ord("j")):
                self.sel = (self.sel + 1) % len(ROWS)
            elif k in (curses.KEY_RIGHT, ord("+"), ord("=")):
                self.nudge(+1)
            elif k in (curses.KEY_LEFT, ord("-"), ord("_")):
                self.nudge(-1)
            elif k in (ord("1"), ord("2"), ord("3"), ord("4")):
                self.step_i = int(chr(k)) - 1
            elif k == ord("h"):
                self.msg = "Re-sending the HOME pose..."
                self.draw()
                self.rig.goto_many(dict(self.home))
                self.msg = "Home pose re-sent (nudges cleared)"
            elif k == ord("t"):
                ch = self.sel_channel()
                self.rig.torque_off(ch)
                self.msg = f"Torque OFF on channel {ch} (move it by hand)"
            elif k == ord("T"):
                self.rig.torque_off()
                self.msg = "Torque OFF on ALL channels"
            elif k == ord("e"):
                ch = self.sel_channel()
                self.rig.torque_on(ch)
                self.msg = f"Channel {ch} re-enabled at last commanded angle"
            elif k == ord("g"):
                self.generate()


def main():
    ap = argparse.ArgumentParser(description="Corndog master reference finder")
    ap.add_argument("--simulate", action="store_true")
    args = ap.parse_args()

    cal = load_calibration()
    home = dict(cal["servo_home"])
    mapping = cal["mapping_right"]

    print()
    print(f"  {GRN}MASTER FINDER{RST}  (source: {cal['source']})")
    print("  -------------")
    print(f"  {YLW}Please place Corndog on his back, or hold him so he doesn't")
    print(f"  push himself around by moving.{RST}")
    print()
    print(f"  {RED}ALL motors turn on and snap to the HOME pose the moment you")
    print(f"  confirm.{RST} Then nudge him into the reference pose and press g.")
    if args.simulate:
        print("  [simulation mode — no hardware will move]")
    else:
        ans = input("  Is he on his back / held safely? [y/N] ").strip().lower()
        if ans != "y":
            print("  Aborted — nothing was moved.")
            sys.exit(1)

    rig = open_rig(args.simulate)
    print("  Energizing all servos to the home pose...")
    rig.goto_many(home)

    ui_holder = {}

    def run(scr):
        ui = UI(scr, rig, home, mapping)
        ui_holder["ui"] = ui
        ui.loop()

    try:
        curses.wrapper(run)
    finally:
        if not args.simulate:
            rig.torque_off()

    ui = ui_holder.get("ui")
    if ui and ui.generated:
        print()
        print(f"  {GRN}--- paste everything below into tools/master_tables.py ---{RST}")
        print()
        print(ui.generated)
        print(f"  {GRN}--- end (also saved to "
              f"{config_dir() / 'master_tables_generated.py'}) ---{RST}")
    else:
        print("  (no tables generated — press g next time before quitting)")


if __name__ == "__main__":
    main()
